# Site settings
title:
email: info@ardanis.com
thanks_url: http://www.ardanis.com/thanks.html
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: "ardanis"
github_username: "ardanistech"

# Build settings
markdown: kramdown
