header:
  title:
  subtitle:
  class: street-and-technology
title: Our Services
summary: <p class="summary-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
categories:
  - name: Development Services
    anchor-name: development
    tagline: realise your<br/><span class="portfolio-box-title-focus">vision</span>
    portfolio-box-image-class: vision
    portfolio-box-content-title: Need to build or improve a software solution?
    portfolio-box-content-text: find out more...
    destination: services.html#development
    details-image: img/internal_mobile.jpg
    details: "<h3>You want to build a product or improve your existing solution, do you need some help?</h3>
      <p>We often hear phrases like:
        <ul>
        	<li>We want to build a product but don’t have the people or time available to build it.</li>
          <li>We know the solution we want but don’t know how to build it.</li>
          <li>We need a solution to a particular problem but don’t know what the solution should be.</li>
          <li>Our products works but our customers complain that is difficult to use</li>
          <li>Our product needs more modern features as it is getting outdated and losing popularity</li>
        </ul>
      If any of the above sounded familiar then Ardanis can help you bring your vision to reality.
      We are passionate about quality software development!  You can rest easy when working with us b
      ecause we use the best practices and technologies to ensure that you get a solution that perfectly
      meets your needs and will be scalable, robust and delivered promptly.</p>
      <h4>How do we help you?</h4>
      Our technical skills and experience to help achieve your vision for your product.  You will be involved
      in the entire process so you can easily observe the progress.  We use the Agile development process to
      ensure that you get the outcome you want.  Agile involves an ongoing series of demonstrations of the
      project’s progress so your feedback identifies any issues we need to resolve early.  As the name
      suggests, Agile is a flexible approach that allows changes to be incorporated quickly and seamlessly.
      It is important that the most suitable technologies are used for your product so that it is robust and
      good value.  Our experienced team will offer you expert advice and options targeted to your product."
  - name: Build Engineering
    anchor-name: engineering
    tagline: increase your<br/><span class="portfolio-box-title-focus">productivity</span>
    portfolio-box-image-class: productivity
    portfolio-box-content-title: Tools and processes can speed up development
    portfolio-box-content-text: find out more...
    destination: services.html#engineering
    details-image: img/internal_serverroom.jpg
    details: "<h3>Do you spend more time on maintenance and bug fixing rather than developing new features?</h3>
      <p>Whether you are building a new product or maintaining existing solutions there are a lot of techniques
      you can use to make it easier and more efficient.  If you have said or heard comments similar to the
      following, we can help you:
      <ul>
        <li>We dread releases!  We often have to rollback releases because of unexpected side effects.</li>
        <li>Our pace of development is not as fast as we’d like.</li>
        <li>Our developers have to spend a significant amount of time maintaining tools and environmental issues
        rather working on new features or releases.</li>
        <li>What the development team produces is not always aligned with what the business users wanted.</li>
      </ul>
      If these sound familiar, don’t worry!  These are very common concerns in software development and there a
      number of convenient solutions.</p>
      <h4>How do we help you?</h4>
      <p>You can overcome issues like those by using some techniques that make development faster and more
      reliable.  We can help you implement and adopt these techniques. Agile, code quality metrics, Test Driven
      Development (TDD), Continuous Integration (CI) and Continuous Deployment (CD) are examples of techniques
      that we can help you implement.  These techniques can make a radical improvement on your productivity.
      These approaches promote the following:
        <ul>
        <li>Developers are more focussed</li>
        <li>Stakeholders and developers communicate regularly</li>
        <li>Product quality; fewer bugs, more robust</li>
        <li>Releases become frequent and automatic (not as scary as it sounds!)</li>
        </ul>
      </p>"

  - name: Developer Resources
    anchor-name: resources
    tagline: expand your<br/><span class="portfolio-box-title-focus">team</span>
    portfolio-box-image-class: team
    portfolio-box-content-title: Looking for skilled people for your project?
    portfolio-box-content-text: find out more...
    destination: services.html#resources
    details-image: img/internal_vr.jpg
    details: "<h3>Need some developers or a technical specialist for your next project?</h3>
      <p>Need some extra people for a particular project? Or do you need a specialist for a particular
      technology?  We may be able to help.  Our team is quite diverse and we like to think we have the technical
      resources to fill most roles you are looking for.  Whether you need a developer to help your team get
      through your backlog of work or you need an architect to work with your business and development teams to
      design a great solution, we may have the ideal person for you.</p>"
