header:
  title:
  subtitle:
  class: street-and-technology
title: Our Services
summary: <p class="summary-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
categories:
  - name: Development Services
    tagline: realise your<br/><span class="portfolio-box-title-focus">vision</span>
    portfolio-box-image-class: vision
    portfolio-box-content-title: Need to build or improve a software solution?
    portfolio-box-content-text: find out more...
    destination: services.html
    details-image: img/internal_mobile.jpg
  - name: Build Engineering Services
    tagline: increase your<br/><span class="portfolio-box-title-focus">productivity</span>
    portfolio-box-image-class: productivity
    portfolio-box-content-title: Tools and processes can speed up development
    portfolio-box-content-text: find out more...
    destination: services.html
    details-image: img/internal_serverroom.jpg
  - name: Developer Resources
    tagline: expand your<br/><span class="portfolio-box-title-focus">team</span>
    portfolio-box-image-class: team
    portfolio-box-content-title: Looking for skilled people for your project?
    portfolio-box-content-text: find out more...
    destination: services.html
    details-image: img/internal_vr.jpg
